### ISSUE TITLE
Can biomass removed be added to summary log?

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Harvest#9]
Matthew Duveneck: "Can biomass removed be added to the harvest_summary_log.csv as well as the harvest_log.csv?"

**Comment by lbross** [comment]
Is Matthew asking for MgBiomassRemoved only? Or would he also like MgBioRemovedPerDamagedHa, and BiomassMg by species (like we just added to the event log)? I added BiomassMg by species this afternoon before checking to see what was already there so that is done. MgBiomassRemoved should be easy to add. Less certain about MgBioRemovedPerDamagedHa as summing the events in a timestep may not necessarily give us an accurate answer.

**Comment by lbross** [comment]
From Matthew: I am interested in MgBiomassRemoved and BiomassMg by species in the summary file. Thanks so much!

**Comment by lbross** [comment]
The requested fields have been added to Biomass Harvest 3.0 rc6 and an installer posted.

**Comment by lbross** [comment]
Verified by Matthew. Released with v3.0
